const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gobsmacked', {
  authStatus: () => ipcRenderer.invoke('auth:status'),
  authSetup: (payload) => ipcRenderer.invoke('auth:setup', payload),
  authSetupInner: (secret) => ipcRenderer.invoke('auth:setupInner', { secret }),
  authVerify: (secret, purpose = 'main', identity = '') => ipcRenderer.invoke('auth:verify', { secret, purpose, identity }),
  authTrustedEnter: () => ipcRenderer.invoke('auth:trustedEnter'),
  setDeviceTrust: (enabled) => ipcRenderer.invoke('auth:setDeviceTrust', Boolean(enabled)),
  lockInner: () => ipcRenderer.invoke('auth:lockInner'),
  getRecord: (kind, date) => ipcRenderer.invoke('record:get', { kind, date }),
  saveRecord: (record) => ipcRenderer.invoke('record:save', record),
  recordIndex: () => ipcRenderer.invoke('record:index'),
  recentRecords: (limit) => ipcRenderer.invoke('record:recent', limit),
  calendarRecords: (month) => ipcRenderer.invoke('record:calendar', month),
  importAsset: (type) => ipcRenderer.invoke('asset:import', type),
  saveRecording: (bytes, mimeType) => ipcRenderer.invoke('asset:saveRecording', { bytes, mimeType }),
  getEarthOutlines: () => ipcRenderer.invoke('earth:outlines'),
  geocodeLocation: (query) => ipcRenderer.invoke('earth:geocode', query),
  listAnnotations: () => ipcRenderer.invoke('annotations:list'),
  saveAnnotation: (payload) => ipcRenderer.invoke('annotations:save', payload),
  deleteAnnotation: (id) => ipcRenderer.invoke('annotations:delete', id),
  getConstellation: () => ipcRenderer.invoke('constellation:get'),
  updateConstellation: (payload) => ipcRenderer.invoke('constellation:update', payload),
  selectLegacyDiary: () => ipcRenderer.invoke('legacy:select'),
  importLegacyEntries: (entries) => ipcRenderer.invoke('legacy:importEntries', { entries }),
  exportContent: () => ipcRenderer.invoke('export:content'),
  exportMigration: () => ipcRenderer.invoke('export:migration'),
  onExportProgress: (listener) => ipcRenderer.on('export:progress', (_event, value) => listener(value)),
  libraryStatus: () => ipcRenderer.invoke('library:status'),
  listLibrary: (relative = '', query = '') => ipcRenderer.invoke('library:list', { relative, query }),
  importLibraryFiles: (relative = '') => ipcRenderer.invoke('library:importFiles', relative),
  importLibraryFolder: (relative = '') => ipcRenderer.invoke('library:importFolder', relative),
  openLibraryItem: (relative) => ipcRenderer.invoke('library:open', relative),
  exportLibraryItem: (relative) => ipcRenderer.invoke('library:export', relative)
});
